---

- meta: flush_handlers

- name: Create a network
  become: true
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ influxdb_docker_networks }}"

- name: Start or restart influxdb container
  become: true
  docker_container:
    name: "{{ influxdb_container_name }}"
    image: influxdb
    state: "{{ influxdb_docker_state | default('started') }}"
    restart: "{{ influxdb_docker_restart | default(false) | bool }}"
    networks: "{{ influxdb_docker_networks }}"
    restart_policy: "{{ influxdb_container_restart_policy }}"
    volumes:
      - "{{ influxdb_conf_location }}/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      - "{{ influxdb_data_location }}:/var/lib/influxdb"
